name: three_d_graph
description: "A Flutter package for rendering 3D graphs, point clouds, and geometric shapes with interactive rotation."
version: 0.1.0
homepage: https://github.com/satri-tech/three_d_graph

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
